AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6
  Exclude:
  - 'node_modules/**/*'
  - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

##############################

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
