AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.7
  Exclude:
  - 'node_modules/**/*'
  - 'vendor/**/*'

Layout/LineLength:
  Max: 80

Style/Documentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/StructInheritance:
  Enabled: false
