language: ruby
rvm: 2.6.1
branches:
  only: master
before_install:
- gem update --system
- gem install bundler
install:
- bundle install --jobs=3 --retry=3 --deployment
- yarn install
script:
- bundle exec rake
- bundle exec rubocop
- yarn test
cache:
- bundler
- yarn
